// AUTO-GENERATED by scripts/gen-migration-list.mjs — do not edit by hand.
// Re-run via `npm run db:generate` or `npm run build`.

export const MIGRATIONS: ReadonlyArray<{ name: string; sql: string }> = [
  { name: "0000_init_submissions", sql: "CREATE TABLE `counters` (\n\t`name` text PRIMARY KEY NOT NULL,\n\t`value` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `submissions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`company_name` text,\n\t`period_end` text,\n\t`hmrc_message_class` text,\n\t`hmrc_status` text DEFAULT 'created' NOT NULL,\n\t`hmrc_correlation_id` text,\n\t`hmrc_poll_endpoint` text,\n\t`hmrc_poll_interval_seconds` integer,\n\t`hmrc_submission_id` text,\n\t`hmrc_irmark` text,\n\t`hmrc_payload_hash` text,\n\t`hmrc_raw_response` text,\n\t`hmrc_message` text,\n\t`ch_status` text,\n\t`ch_message` text,\n\t`ch_transaction_id` text,\n\t`ch_submission_number` text,\n\t`ch_raw_response` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n" },
]
